import type { Supplier } from "@/lib/engine/types";

/** 新用户首登时播种的默认供应商档案，便于立即体验。 */
export const SEED_SUPPLIERS: Omit<Supplier, "createdAt">[] = [
  {
    id: "lumen-viet",
    name: "Lumen Viet Manufacturing",
    codeName: "LUMEN VIET",
    region: "越南 · 胡志明市",
    countryCode: "VN",
    restrictedRegion: false,
    preferredChain: "base",
    preferredCoin: "USDC",
    payoutAddress: "0x7a3f…c19d",
    travelRuleCompleteness: 0.72,
    addressNetworkMatch: true,
    paymentCount: 24,
    historicalReturnRate: 0.021,
    avgSettlementHours: 2.4,
    avgAmountUsd: 12800,
  },
  {
    id: "nordwind-dev",
    name: "Nordwind Dev Studio",
    codeName: "NORDWIND",
    region: "爱沙尼亚 · 塔林",
    countryCode: "EE",
    restrictedRegion: false,
    preferredChain: "arbitrum",
    preferredCoin: "USDC",
    payoutAddress: "0x91b2…4fa7",
    travelRuleCompleteness: 0.98,
    addressNetworkMatch: true,
    paymentCount: 41,
    historicalReturnRate: 0.006,
    avgSettlementHours: 1.6,
    avgAmountUsd: 9400,
  },
  {
    id: "sahana-design",
    name: "Sahana Design House",
    codeName: "SAHANA",
    region: "印度 · 班加罗尔",
    countryCode: "IN",
    restrictedRegion: false,
    preferredChain: "polygon",
    preferredCoin: "USDC",
    payoutAddress: "0x3d8e…a012",
    travelRuleCompleteness: 0.88,
    addressNetworkMatch: false,
    paymentCount: 12,
    historicalReturnRate: 0.058,
    avgSettlementHours: 4.1,
    avgAmountUsd: 5600,
  },
  {
    id: "meridian-freight",
    name: "Meridian Freight OU",
    codeName: "MERIDIAN",
    region: "受限地区 · 待复核",
    countryCode: "XX",
    restrictedRegion: true,
    preferredChain: "tron",
    preferredCoin: "USDT",
    payoutAddress: "TQ9f…8m2k",
    travelRuleCompleteness: 0.61,
    addressNetworkMatch: true,
    paymentCount: 5,
    historicalReturnRate: 0.11,
    avgSettlementHours: 6.2,
    avgAmountUsd: 7200,
  },
];
