import type { Supplier } from "@/lib/engine/types";

/** Default payee ledger seeded on first login so the app is immediately usable. */
export const SEED_SUPPLIERS: Omit<Supplier, "createdAt">[] = [
  {
    id: "lumen-viet",
    name: "Lumen Viet Manufacturing Co",
    codeName: "LUMEN VIET",
    country: "Vietnam · Ho Chi Minh City",
    countryCode: "VN",
    currency: "VND",
    entityType: "overseas",
    bankName: "Vietcombank",
    swift: "BFTVVNVX",
    iban: "VN82BFTV0123456789012",
    accountStatus: "active",
    restrictedRegion: false,
    bankBlacklisted: false,
    preferredChannel: "local-fiat",
    riskTag: "medium",
    paymentCount: 24,
    historicalReturnRate: 0.021,
    avgSettlementHours: 12,
    avgAmountUsd: 12800,
  },
  {
    id: "nordwind-dev",
    name: "Nordwind Dev OU",
    codeName: "NORDWIND",
    country: "Estonia · Tallinn",
    countryCode: "EE",
    currency: "EUR",
    entityType: "overseas",
    bankName: "LHV Pank",
    swift: "LHVBEE22",
    iban: "EE471000001020145685",
    accountStatus: "active",
    restrictedRegion: false,
    bankBlacklisted: false,
    preferredChannel: "stablecoin-direct",
    riskTag: "low",
    paymentCount: 41,
    historicalReturnRate: 0.006,
    avgSettlementHours: 20,
    avgAmountUsd: 9400,
  },
  {
    id: "sahana-design",
    name: "Sahana Design House",
    codeName: "SAHANA",
    country: "India · Bengaluru",
    countryCode: "IN",
    currency: "INR",
    entityType: "overseas",
    bankName: "HDFC Bank",
    swift: "HDFCINBB",
    // Intentionally malformed IBAN → triggers the IBAN validation factor.
    iban: "IN00HDFC1",
    accountStatus: "dormant",
    restrictedRegion: false,
    bankBlacklisted: false,
    preferredChannel: "local-fiat",
    riskTag: "medium",
    paymentCount: 12,
    historicalReturnRate: 0.058,
    avgSettlementHours: 30,
    avgAmountUsd: 5600,
  },
  {
    id: "meridian-freight",
    name: "Meridian Freight",
    codeName: "MERIDIAN",
    country: "High-risk region · under review",
    countryCode: "XX",
    currency: "AED",
    entityType: "overseas",
    bankName: "Offshore Trust Bank",
    swift: "OFFSXX00",
    iban: "AE070331234567890123456",
    accountStatus: "unverified",
    restrictedRegion: true,
    bankBlacklisted: true,
    preferredChannel: "stablecoin-direct",
    riskTag: "high",
    paymentCount: 5,
    historicalReturnRate: 0.11,
    avgSettlementHours: 60,
    avgAmountUsd: 7200,
  },
  {
    id: "atlas-domestic",
    name: "Atlas Domestic Logistics LLC",
    codeName: "ATLAS",
    country: "United States · Chicago",
    countryCode: "US",
    currency: "USD",
    entityType: "domestic",
    bankName: "JPMorgan Chase",
    swift: "CHASUS33",
    iban: "US64CHAS0987654321000",
    accountStatus: "active",
    restrictedRegion: false,
    bankBlacklisted: false,
    preferredChannel: "stablecoin-direct",
    riskTag: "low",
    paymentCount: 18,
    historicalReturnRate: 0.009,
    avgSettlementHours: 16,
    avgAmountUsd: 10400,
  },
];
